### ISSUE TITLE
Dist has error

### ISSUE THREAD

**Issue by sgentile** [SMARTDATASYSTEMSLLC/generator-sds-angular#4]
After running grunt build - when running the app from the dist folder I get the following error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.8/$injector/nomod?p0=app
    at http://localhost:8000/scripts/vendor.60b83812.js:3:31521
    at http://localhost:8000/scripts/vendor.60b83812.js:4:7758
    at b (http://localhost:8000/scripts/vendor.60b83812.js:4:7330)
    at http://localhost:8000/scripts/vendor.60b83812.js:4:7642
    at http://localhost:8000/scripts/vendor.60b83812.js:4:16146
    at f (http://localhost:8000/scripts/vendor.60b83812.js:3:31906)
    at n (http://localhost:8000/scripts/vendor.60b83812.js:4:15924)
    at Sb (http://localhost:8000/scripts/vendor.60b83812.js:4:17586)
    at h (http://localhost:8000/scripts/vendor.60b83812.js:4:5510)
    at _ (http://localhost:8000/scripts/vendor.60b83812.js:4:5820)
http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=app&p1=Error%3A%20%…20(http%3A%2F%2Flocalhost%3A8000%2Fscripts%2Fvendor.60b83812.js%3A4%3A5820)

**Comment by dben** [comment]
a6c60399b137f1e24bab74a6dca64d877d5162da fixed. The partials were broken, so I removed them.
