### ISSUE TITLE
Error generating service

### ISSUE THREAD

**Issue by sgentile** [SMARTDATASYSTEMSLLC/generator-sds-angular#5]
using the following:
 yo sds-angular:service api

(note, by default it's trying to install it in app/api instead of app/services/api)

? Where would you like to create the service files? app/services/api/
? app/services does not exist.  Create it? Yes

dir app/services/api/
customTemplateName api-spec.js
dir app/services/api/
customTemplateName api.js
app/services/api/api.js 

/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8913
                throw e;
                      ^
TypeError: Cannot read property 'js' of undefined
    at Object.exports.inject (/usr/local/lib/node_modules/generator-sds-angular/utils.js:76:43)
    at /usr/local/lib/node_modules/generator-sds-angular/utils.js:57:21
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/local/lib/node_modules/generator-sds-angular/node_modules/underscore/underscore.js:79:11)
    at _.(anonymous function) [as each] (/usr/local/lib/node_modules/generator-sds-angular/node_modules/underscore/underscore.js:1123:39)
    at Object.exports.processTemplates (/usr/local/lib/node_modules/generator-sds-angular/utils.js:48:10)
    at ServiceGenerator.files (/usr/local/lib/node_modules/generator-sds-angular/service/index.js:41:13)
    at /usr/local/lib/node_modules/generator-sds-angular/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-sds-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-sds-angular

**Comment by dben** [comment]
a6c60399b137f1e24bab74a6dca64d877d5162da fixed this. reverted the demo page skeleton to fix.

**Comment by sgentile** [comment]
Why would adding some pages break the generator?

**Comment by dben** [comment]
I'm not sure, but it seemed to be working when I tested it on a new site
after I reverted - let me know if that isn't the case
